Add JMeter example application
green-coding-berlin/example-applications pull request #51
Opened 2023-12-05 20:01 UTC by davidkopp

This example demonstrates how to use JMeter to execute a test plan that makes HTTP requests to a web application.
[Apache JMeter](https://jmeter.apache.org/) is a load and performance testing tool.

JMeter Docker image: https://hub.docker.com/r/t2project/jmeter
Example web application: [T2-Project](https://t2-documentation.readthedocs.io)

2023-12-06 07:16 UTC, ArneTR requested changes
Hey @davidkopp 

The flow of great PRs keeps coming. I love it!

Again a very high quality PR!!

When we take in examples from externals we always like to pin the depencies with a hash. This keeps the security issues lower and also increases reproducibility for people using your example.
I made two requests at the corresponding locations.

Hope that is ok to request!

If you however had in mind to use the example to track the changes over time by only referencing the github here, we can also talk about bringing that into our timeline project. Let me know! - https://metrics.green-coding.berlin/energy-timeline.html

2023-12-06 07:16 UTC, ArneTR commented on jmeter/compose.yml
> +    image: t2project/modulith:gmt-jmeter-example
can you pin this with a hash

2023-12-06 07:16 UTC, ArneTR commented on jmeter/compose.yml
> +    image: t2project/jmeter:5.6.2
can you pin this with a hash

2023-12-06 07:16 UTC, ArneTR commented on jmeter/jmeter-test-plan.jmx
> +log.info(&quot;${currentTimeMicroseconds} GMT_SCI_R=1&quot;)</stringProp>
Love it!

2023-12-06 09:30 UTC, davidkopp commented
It's ok for me to pin the images with hashes :)

2023-12-14 06:56 UTC, ArneTR commented
lgtm

2023-12-14 06:56 UTC, merged

2023-12-14 06:57 UTC, ArneTR commented
@dan-mm Can you have a look at this if it gets picked up by our example applications routine testing. Having a java jmeter application in there is very valueable.

Also please report how long it takes for this test to run on our infrastructure

2023-12-14 13:16 UTC, dan-mm commented
@ArneTR - tested it out. It does indeed get picked up by the example applications, I just ran the tests manually and saw it picked up and pass.

To answer the time question, its about 1 - 2 minutes. Considering the entire example apps test suite takes 3.5 hours its nothing. I double checked by pulling and running the smoketest on this directory alone, it takes between 53 seconds - 2 minutes to complete.